import os

ENVIRONMENT = os.getenv("ENVIRONMENT")

WEB_APPLICATION_HOST = os.getenv("WEB_APPLICATION_HOST")
DATA_COLLECTOR_HOST = os.getenv("DATA_COLLECTOR_HOST")
DATA_ANALYZER_HOST = os.getenv("DATA_ANALYZER_HOST")

WEB_APPLICATION_PORT = os.getenv("WEB_APPLICATION_PORT")
DATA_COLLECTOR_PORT = os.getenv("DATA_COLLECTOR_PORT")
DATA_ANALYZER_PORT = os.getenv("DATA_ANALYZER_PORT")


DATA_ANALYZER_ENDPOINT = ("" if ENVIRONMENT == "PROD" else "http://") + DATA_ANALYZER_HOST + ":" + DATA_ANALYZER_PORT
WEB_APPLICATION_ENDPOINT = ("" if ENVIRONMENT == "PROD" else "http://") + WEB_APPLICATION_HOST + ":" + WEB_APPLICATION_PORT
DATA_COLLECTOR_ENDPOINT = ("" if ENVIRONMENT == "PROD" else "http://") + DATA_COLLECTOR_HOST + ":" + DATA_COLLECTOR_PORT

DATABASE_URL = os.getenv("DATABASE_URL")
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")
DB_NAME = os.getenv("DB_NAME")
DB_USERNAME = os.getenv("DB_USERNAME")
DB_PASSWORD = os.getenv("DB_PASSWORD")

request_header={"Content-Type": "application/json"}
