name: CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.14'
          cache: 'pip' 
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Create .env file
        run: |
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
      - name: Run Tests
        run: pytest
        env:
          ENV: local
          PYTHONPATH: .
          DB_NAME: defaultdb
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: 25060
          DATA_COLLECTOR_PORT: 9081
          DATA_ANALYZER_PORT: 9091
          WEB_APPLICATION_PORT: 8082


  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to dokku
        uses: dokku/github-action@v1.4.0
        with:
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          git_remote_url: ssh://dokku@157.245.129.75:22/newsdatawebapp
          branch: main
          git_push_flags: --force
          command: deploy
